config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'mains#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks, dependent: :destroy
    validates :name, presence: true, length: { maximum: 15 }, uniqueness: { scope: :user, message: "category name is already taken" }
    validates :description, presence: true, length: { maximum: 60 }
    belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category
    validates :name, presence: true, length: { maximum: 20 }, uniqueness: { scope: :category, message: "task name is already taken" }
    validates :description, presence: true
    validates :deadline, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    include Devise::Controllers::Helpers 
    before_action :authenticate_user!
    def index
        @categories = current_user.categories.all
    end
    
    def show
        @category = current_user.categories.find(params[:id])
        @tasks = @category.tasks.all
    end
    
    def new
        @category = current_user.categories.build
    end
    
    def create
        @category = current_user.categories.build(category_params)
    
        if @category.valid?
            @category.save
            redirect_to @category
        else
          render :new
        end
    end
    
    def edit
        @category = current_user.categories.find(params[:id])
    end
    
    def update
        @category = current_user.categories.find(params[:id])
    
        if @category.update(category_params)
          redirect_to @category
        else
          render :edit
        end
    end
    
    def destroy
        @category = current_user.categories.find(params[:id])
        @category.destroy

        redirect_to categories_path
    end
    
    private

    def category_params
        params.require(:category).permit(:name, :description)
    end

end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  def home
    @categories = current_user.categories.all if current_user != nil
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    include Devise::Controllers::Helpers 
    before_action :authenticate_user!
    before_action :get_category

    def index
        @tasks = @category.tasks.all
        redirect_to category_path(@category)
    end
    
    def show
        @task = @category.tasks.find(params[:id])
    end
    
    def new
        @task = @category.tasks.build
    end
    
    def create
        @task =  @category.tasks.build(task_params)
        
        if @task.valid?
            @task.save
            redirect_to (params[:previous_request] || category_path(@category))
        else
          render :new
        end
    end
    
    def edit
        @task = @category.tasks.find(params[:id])
    end
    
    def update
        @task = @category.tasks.find(params[:id])
    
        if @task.update(task_params)
            redirect_to (params[:previous_request] || category_path(@category))
        else
          render :edit
        end
    end
    
    def destroy
        @task = @category.tasks.find(params[:id])
        @task.destroy

        redirect_to category_path(@category)
    end
    
    private

    def get_category
        @category = current_user.categories.find(params[:category_id])
    end

    def task_params
        params.require(:task).permit(:name, :description, :deadline, :finish)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category do |f| %>
  <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
    <section class="w-full px-8 py-6 bg-blue-100 xl:px-8">
        <div class="max-w-5xl mx-auto">
            <div class="flex flex-col items-center md:flex-row">

                <div class="w-full space-y-5 md:w-3/5 md:pr-16">
                    <div class="w-3/4 h-3/4 bg-white">
                      <%= image_tag("Category.png", class:"w-full") %>
                    </div>
                </div>

                <div class="w-full mt-16 md:mt-0 md:w-2/5">
                    <div class="relative z-10 h-auto p-8 py-10 overflow-hidden bg-white border-b-2 border-gray-300 rounded-lg shadow-2xl px-7">
                        <h3 class="mb-6 text-2xl font-medium text-center">CATEGORY Details</h3>
                        <% category.errors.full_messages_for(:name).each do |message| %>
                          <div class="text-red-500"><%= message %></div>
                        <% end %>
                        <% category.errors.full_messages_for(:description).each do |message| %>
                          <div class="text-red-500"><%= message %></div>
                        <% end %>
                        <%= f.text_field :name, class:"block w-full px-4 py-3 mb-4 border border-2 border-transparent border-gray-200 rounded-lg focus:ring focus:ring-blue-500 focus:outline-none", placeholder:"Category Name" %>
                        <%= f.text_area :description, class:"block w-full px-4 py-3 mb-4 border border-2 border-transparent border-gray-200 rounded-lg resize-none focus:ring focus:ring-blue-500 focus:outline-none", placeholder:"Description" %>
                        <div class="block">
                            <%= f.submit class:"w-full px-3 py-4 font-medium text-white bg-blue-600 rounded-lg cursor-pointer"%>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <%= link_to :back do %>
          <div class="h-10 w-10 mt-4 flex items-center rounded justify-center hover:bg-gray-100">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-full w-full" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
          </div>
        <% end %>
    </section>
  </div>


<% end %>

app/views/categories/edit.html.erb
<header class="bg-white shadow">
  <div class="w-2/5 mx-auto text-center py-6 px-4 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold text-gray-900">
      Edit CATEGORY
    </h1>
  </div>
</header>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
  <header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold text-gray-900">
      CATEGORIES
    </h1>
    </div>
  </header>

  <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">  
    <div class="px-4 py-6 sm:px-0">
      <div class="border-4 border-dashed border-gray-200 rounded-lg h-96">
        <% @categories.sort_by { |c| c["updated_at"] }.reverse.each do |category| %>
          <h2 class="text-center"><%= link_to category.name, category %></h2>
        <% end %>
        <%= link_to "Back", :back %>
        <%= link_to "CREATE", new_category_path %>
      </div>
    </div>
  </div>

app/views/categories/new.html.erb
<header class="bg-white shadow">
  <div class="w-2/5 mx-auto text-center py-6 px-4 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold text-gray-900">
      Create a CATEGORY
    </h1>
  </div>
</header>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<header data-controller="category" class="bg-white shadow w-full">
  <div class="w-2/5 mx-auto py-6 px-4 sm:px-6 lg:px-8">
    <h1 data-action="mouseover->category#show mouseout->category#hide" class="text-3xl text-center font-bold text-gray-900 hover:text-blue-900 cursor-pointer">
      <%= link_to "Category: #{@category.name}", edit_category_path(@category) %>
    </h1>
  </div>

  <div data-category-target="description" class="absolute top-16 right-1/3 bg-white rounded border-2 border-blue-900 h-20 w-40 flex flex-wrap items-center hidden">
    <p class="text-xs text-center"><%= @category.description %></p>
  </div>

  <div class="hidden">
    <%= link_to "Delete", category_path(@category), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</header>



<%= render 'tasks/index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskMaster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="https://i1.wp.com/www.pamelaweaver.com/wp-content/uploads/2015/04/tasks.png?ssl=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="relative min-h-screen overflow-hidden flex">
      <% if user_signed_in? %>
        <%= render 'mains/sidenav' %>
      <% end %>

      <div class="flex-1">
        <% if notice %>
          <%= render 'mains/notice' %>
        <% end %>
      
        <%= yield %>
      </div>

  </body>
</html>

app/views/mains/_footer.html.erb
<section class="text-gray-700 bg-white body-font">
    <div class="container flex flex-col items-center px-8 py-8 mx-auto max-w-7xl sm:flex-row">
        <a href="#_" class="text-xl font-black leading-none text-gray-900 select-none logo">TaskMaster<span class="text-indigo-600">.</span></a>
        <p class="mt-4 text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l sm:border-gray-200 sm:mt-0">© 2021 Tails - Tailwindcss Page Builder
          </p>
          <span class="inline-flex justify-center mt-4 space-x-5 sm:ml-auto sm:mt-0 sm:justify-start">
              <a href="#" class="text-gray-400 hover:text-gray-500">
                  <span class="sr-only">Facebook</span>
                  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                      <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd"></path>
                  </svg>
              </a>

              <a href="#" class="text-gray-400 hover:text-gray-500">
                  <span class="sr-only">Instagram</span>
                  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                      <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd"></path>
                  </svg>
              </a>

              <a href="#" class="text-gray-400 hover:text-gray-500">
                  <span class="sr-only">Twitter</span>
                  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                      <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"></path>
                  </svg>
              </a>

              <a href="#" class="text-gray-400 hover:text-gray-500">
                  <span class="sr-only">GitHub</span>
                  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                      <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd"></path>
                  </svg>
              </a>

              <a href="#" class="text-gray-400 hover:text-gray-500">
                  <span class="sr-only">Dribbble</span>
                  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                      <path fill-rule="evenodd" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z" clip-rule="evenodd"></path>
                  </svg>
              </a>
          </span>
    </div>
</section>

app/views/mains/_notice.html.erb
<div data-controller="notice" data-action="click->notice#close" data-notice-target="noticeMessage" class="bg-yellow-100 text-green-600 px-3 py-4 border-t-4 border-yellow-200 shadow-xl flex justify-end items-center w-max absolute top-0 right-0 cursor-auto">
    <%= notice %>
</div>

app/views/mains/_sidenav.html.erb
<div class="bg-blue-800 text-blue-100 w-72 space-y-7 px-2.5 py-8">
    <a class="text-white flex items-center space-x-2 px-5">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" viewBox="0 0 20 20" fill="currentColor">
        <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" />
        <path fill-rule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z" clip-rule="evenodd" />
        </svg>
        <span class="text-3xl font-extrabold">TaskMaster</span>
    </a>
    <nav>
        <%= link_to "Home Page", root_path, class:"block py-3 px-5 rounded transition duration-200 hover:bg-blue-700 cursor-pointer hover:text-white" %>
        <%= link_to "Edit Credentials", edit_user_registration_path, class:"block py-3 px-5 rounded transition duration-200 hover:bg-blue-700 cursor-pointer hover:text-white" %>
        <%= link_to "All Categories", categories_path, class:"block py-3 px-5 rounded transition duration-200 hover:bg-blue-700 cursor-pointer hover:text-white" %>
        <%= link_to "Log Out",  destroy_user_session_path, method: :delete, class:"block py-3 px-5 rounded transition duration-200 hover:bg-blue-700 cursor-pointer hover:text-white" %>
    </nav>

    <div>
      <h1 class="font-bold text-center">TASK COLOR CODING</h1>
      <div class="flex flex-wrap justify-around items-center bg-blue-800 text-lg text-gray-900">
        <h2 class="m-1 bg-red-400 w-24 h-20 flex justify-center items-center">Past Due</h2>
        <h2 class="m-1 bg-yellow-100 w-24 h-20 flex justify-center items-center">Due Today</h2>
        <h2 class="m-1 bg-blue-400 w-24 h-20 flex justify-center items-center">Upcoming</h2>
        <h2 class="m-1 bg-green-300 w-24 h-20 flex justify-center items-center">Finished</h2>
      </div>
    </div>
</div>

app/views/tasks/_categorychoice.html.erb
<div class="h-4/5 w-4/5 bg-gray-100 rounded">
  <header class="bg-white shadow rounded">
    <div class="w-1/2 mx-auto py-6 px-4 sm:px-6 lg:px-8 text-center">
    <h1 class="text-3xl font-bold text-gray-900">
      Choose or <%= link_to "CREATE", new_category_path, class:"text-blue-800 hover:text-green-800" %> a Category
    </h1>
    </div>
  </header>

  <div class="max-w-7xl mx-auto h-screen py-6 sm:px-6 lg:px-8">  
      <div class="flex flex-wrap justify-around border-4 border-dashed border-gray-200 rounded-lg h-2/3 overflow-y-auto">
        <% @categories.sort_by { |c| c["updated_at"] }.reverse.each do |category| %>
          <%= link_to new_category_task_path(category) do %>
            <div class="h-40 w-40 m-4 text-center text-2xl font-bold text-white flex items-center justify-center border-2 border-blue-800 bg-blue-800 rounded-full hover:bg-white hover:text-blue-800">
              <%= category.name %>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<header class="bg-white shadow">
  <div class="w-3/5 mx-auto text-center py-6 px-4 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold text-gray-900">
       Modify TASK from <%= link_to @category.name, category_path(@category), class:"hover:text-blue-800 cursor-pointer" %>
    </h1>
  </div>
</header>

<%= render "form", task: @task, category: @category %>

app/views/tasks/new.html.erb
<header class="bg-white shadow">
  <div class="w-3/5 mx-auto text-center py-6 px-4 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold text-gray-900">
       Add new TASK to <%= link_to @category.name, category_path(@category), class:"hover:text-blue-800 cursor-pointer" %>
    </h1>
  </div>
</header>

<%= render "form", task: @task, category: @category %>

app/views/tasks/show.html.erb
<header class="bg-white shadow">
  <div class="w-3/5 mx-auto text-center py-6 px-4 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold text-gray-900">
       The TASK from <%= link_to @category.name, category_path(@category), class:"hover:text-blue-800 cursor-pointer" %>
    </h1>
  </div>
</header>

<div class="max-w-7xl mx-auto py-3 sm:px-6 lg:px-8">
    <section class="w-full px-8 py-4 bg-blue-100 xl:px-8">
        <div class="max-w-5xl mx-auto">
            <div class="flex flex-col items-center md:flex-row">

                <div class="w-full space-y-5 md:w-3/5 md:pr-16">
                    <div class="w-3/4 h-3/4 bg-white">
                      <%= image_tag("Task.png", class:"w-full") %>
                    </div>
                </div>

                <div class="w-full mt-16 md:mt-0 md:w-2/5">
                    <%= link_to edit_category_task_path(@category, @task) do %>
                    <div class="relative z-10 h-96 p-8 py-10 overflow-hidden bg-white border-b-2 border-gray-300 shadow-2xl px-7 hover:bg-gray-100 cursor-pointer">
                        <h3 class="mb-6 text-3xl font-bold text-center"><%= @task.name %></h3>
                        <h4 class="mb-6 text-lg text-indigo-900 font-bold text-center"><%= "DEADLINE: #{@task.deadline.to_s(:long)}" %></h4>
  
                        <div class="flex flex-start items-center justify-center w-full mb-6">
                          <h4 class="font-bold">Status:</h4>
                          <% if @task.deadline < Date.today && @task.finish == false %>
                            <h4 class="m-1 bg-red-400 w-24 h-8 flex justify-center items-center font-bold">Past Due</h4>
                          <% elsif @task.deadline == Date.today && @task.finish == false %>
                            <h4 class="m-1 bg-yellow-100 w-24 h-8 flex justify-center items-center font-bold">Due Today</h4>
                          <% elsif @task.deadline > Date.today && @task.finish == false %>
                            <h4 class="m-1 bg-blue-400 w-24 h-8 flex justify-center items-center font-bold">Upcoming</h4>
                          <% elsif @task.finish == true %>
                            <h4 class="m-1 bg-green-300 w-24 h-8 flex justify-center items-center font-bold">Finished</h4>
                          <% end %>
                        </div>

                        <div class="overflow-y-auto bg-indigo-100 w-full h-32">
                          <%= @task.description %>
                        </div>  
                    </div>
                    <% end %>

                </div>
            </div>
        </div>
        <div class="flex justify-between">
        <%= link_to :back do %>
          <div class="h-10 w-10 flex items-center rounded justify-center hover:bg-gray-100">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-full w-full" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
          </div>
        <% end %>

        <%= link_to category_task_path(@category,@task), method: :delete, data: { confirm: "Are you sure?" } do %>
          <div class="h-10 w-10 flex items-center rounded justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-full w-full text-red-600 hover:text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
          </div>
        <% end %>

        </div>
    </section>
</div>